export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const DELETE_FROM_BASKET = 'DELETE_FROM_BASKET';
export const DELETE_FROM_BASKET_MANY = 'DELETE_FROM_BASKET_MANY';
export const ADD_TO_CHECKOUT = 'ADD_TO_CHECKOUT';
export const DELETE_FROM_CHECKOUT = 'DELETE_FROM_CHECKOUT';
export const CLEAR_CHECKOUT = 'CLEAR_CHECKOUT';
export const SET_ORDERS = 'SET_ORDERS';
